##Mastercated encrypt payload
mastercard:
  api:
    environment:
      base-path:  https://sandbox.api.mastercard.com/elevate  # Refers to sandbox endpoint
    authentication:
      key-file:  # Copy .p12 file in src/main/resources and set value as classpath:Develop-sandbox.p12.p12
      consumer-key:  # Copy the Consumer key from "Sandbox/Production Keys" section on your project page
      keystore-alias:   # Alias of your key. Default key alias for sandbox is keyalias
      keystore-password:  # Password of your Keystore. Default keystore password for sandbox project is keystorepassword
    encryption:
      key-file:   #client-encryption.pem
      fingerprint:  #fingerprint
#Logging level
logging:
  level:
    org.springframework.web: DEBUG
    guru.springframework.controllers: DEBUG
    org.hibernate: DEBUG
server:
  port: 8081

spring:
  main:
    allow-bean-definition-overriding: true